//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agents
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealizationProduct
    {
        public int AgentId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime DataRealization { get; set; }
        public int ProductCount { get; set; }
        public int IdRP { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }
    }
}
