//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payments.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsUser
    {   public int Id { get; set; }
        public System.DateTime DatePayment { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Discription { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost {
            get { return this.Count * this.Price; }
            set { } }
        public Nullable<int> UserId { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
