//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class works_on
    {
        public int emp_no { get; set; }
        public string project_no { get; set; }
        public string job { get; set; }
        public Nullable<System.DateTime> enter_date { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual project project { get; set; }
    }
}
